version: '3.8'

services:
  portfolio:
    image: aryan/portfolio-app:latest
    build:
      context: .
    ports:
      - 8080:3000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
